//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightClient.Flight {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Flight.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InformationSpecifiedRoute", ReplyAction="http://tempuri.org/IService1/InformationSpecifiedRouteResponse")]
        string InformationSpecifiedRoute(string numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InformationSpecifiedRoute", ReplyAction="http://tempuri.org/IService1/InformationSpecifiedRouteResponse")]
        System.Threading.Tasks.Task<string> InformationSpecifiedRouteAsync(string numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookTickets", ReplyAction="http://tempuri.org/IService1/BookTicketsResponse")]
        string BookTickets(int numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookTickets", ReplyAction="http://tempuri.org/IService1/BookTicketsResponse")]
        System.Threading.Tasks.Task<string> BookTicketsAsync(int numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numberFlightInfo", ReplyAction="http://tempuri.org/IService1/numberFlightInfoResponse")]
        string numberFlightInfo(string startPoint, string destinationPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/numberFlightInfo", ReplyAction="http://tempuri.org/IService1/numberFlightInfoResponse")]
        System.Threading.Tasks.Task<string> numberFlightInfoAsync(string startPoint, string destinationPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFlight", ReplyAction="http://tempuri.org/IService1/AddFlightResponse")]
        void AddFlight(int numberFlight, string startPoint, string destinationPoint, int quantityTickets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFlight", ReplyAction="http://tempuri.org/IService1/AddFlightResponse")]
        System.Threading.Tasks.Task AddFlightAsync(int numberFlight, string startPoint, string destinationPoint, int quantityTickets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangesFlightQuantityTickets", ReplyAction="http://tempuri.org/IService1/ChangesFlightQuantityTicketsResponse")]
        void ChangesFlightQuantityTickets(int numberFlight, int quantityTickets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangesFlightQuantityTickets", ReplyAction="http://tempuri.org/IService1/ChangesFlightQuantityTicketsResponse")]
        System.Threading.Tasks.Task ChangesFlightQuantityTicketsAsync(int numberFlight, int quantityTickets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelFlight", ReplyAction="http://tempuri.org/IService1/DelFlightResponse")]
        void DelFlight(int numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelFlight", ReplyAction="http://tempuri.org/IService1/DelFlightResponse")]
        System.Threading.Tasks.Task DelFlightAsync(int numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FullFlight", ReplyAction="http://tempuri.org/IService1/FullFlightResponse")]
        string FullFlight();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FullFlight", ReplyAction="http://tempuri.org/IService1/FullFlightResponse")]
        System.Threading.Tasks.Task<string> FullFlightAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FlightClient.Flight.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FlightClient.Flight.IService1>, FlightClient.Flight.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InformationSpecifiedRoute(string numberFlight) {
            return base.Channel.InformationSpecifiedRoute(numberFlight);
        }
        
        public System.Threading.Tasks.Task<string> InformationSpecifiedRouteAsync(string numberFlight) {
            return base.Channel.InformationSpecifiedRouteAsync(numberFlight);
        }
        
        public string BookTickets(int numberFlight) {
            return base.Channel.BookTickets(numberFlight);
        }
        
        public System.Threading.Tasks.Task<string> BookTicketsAsync(int numberFlight) {
            return base.Channel.BookTicketsAsync(numberFlight);
        }
        
        public string numberFlightInfo(string startPoint, string destinationPoint) {
            return base.Channel.numberFlightInfo(startPoint, destinationPoint);
        }
        
        public System.Threading.Tasks.Task<string> numberFlightInfoAsync(string startPoint, string destinationPoint) {
            return base.Channel.numberFlightInfoAsync(startPoint, destinationPoint);
        }
        
        public void AddFlight(int numberFlight, string startPoint, string destinationPoint, int quantityTickets) {
            base.Channel.AddFlight(numberFlight, startPoint, destinationPoint, quantityTickets);
        }
        
        public System.Threading.Tasks.Task AddFlightAsync(int numberFlight, string startPoint, string destinationPoint, int quantityTickets) {
            return base.Channel.AddFlightAsync(numberFlight, startPoint, destinationPoint, quantityTickets);
        }
        
        public void ChangesFlightQuantityTickets(int numberFlight, int quantityTickets) {
            base.Channel.ChangesFlightQuantityTickets(numberFlight, quantityTickets);
        }
        
        public System.Threading.Tasks.Task ChangesFlightQuantityTicketsAsync(int numberFlight, int quantityTickets) {
            return base.Channel.ChangesFlightQuantityTicketsAsync(numberFlight, quantityTickets);
        }
        
        public void DelFlight(int numberFlight) {
            base.Channel.DelFlight(numberFlight);
        }
        
        public System.Threading.Tasks.Task DelFlightAsync(int numberFlight) {
            return base.Channel.DelFlightAsync(numberFlight);
        }
        
        public string FullFlight() {
            return base.Channel.FullFlight();
        }
        
        public System.Threading.Tasks.Task<string> FullFlightAsync() {
            return base.Channel.FullFlightAsync();
        }
    }
}
