//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Flight {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Flight.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InformationSpecifiedRoute", ReplyAction="http://tempuri.org/IService1/InformationSpecifiedRouteResponse")]
        string InformationSpecifiedRoute(string startPoint, string destinationPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InformationSpecifiedRoute", ReplyAction="http://tempuri.org/IService1/InformationSpecifiedRouteResponse")]
        System.Threading.Tasks.Task<string> InformationSpecifiedRouteAsync(string startPoint, string destinationPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NumberTickets", ReplyAction="http://tempuri.org/IService1/NumberTicketsResponse")]
        string NumberTickets(string numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NumberTickets", ReplyAction="http://tempuri.org/IService1/NumberTicketsResponse")]
        System.Threading.Tasks.Task<string> NumberTicketsAsync(string numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookTickets", ReplyAction="http://tempuri.org/IService1/BookTicketsResponse")]
        string BookTickets(string numberFlight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookTickets", ReplyAction="http://tempuri.org/IService1/BookTicketsResponse")]
        System.Threading.Tasks.Task<string> BookTicketsAsync(string numberFlight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Calculator.Flight.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Calculator.Flight.IService1>, Calculator.Flight.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InformationSpecifiedRoute(string startPoint, string destinationPoint) {
            return base.Channel.InformationSpecifiedRoute(startPoint, destinationPoint);
        }
        
        public System.Threading.Tasks.Task<string> InformationSpecifiedRouteAsync(string startPoint, string destinationPoint) {
            return base.Channel.InformationSpecifiedRouteAsync(startPoint, destinationPoint);
        }
        
        public string NumberTickets(string numberFlight) {
            return base.Channel.NumberTickets(numberFlight);
        }
        
        public System.Threading.Tasks.Task<string> NumberTicketsAsync(string numberFlight) {
            return base.Channel.NumberTicketsAsync(numberFlight);
        }
        
        public string BookTickets(string numberFlight) {
            return base.Channel.BookTickets(numberFlight);
        }
        
        public System.Threading.Tasks.Task<string> BookTicketsAsync(string numberFlight) {
            return base.Channel.BookTicketsAsync(numberFlight);
        }
    }
}
